/*******************************************
Instruction to run this code:
1) ./client Num      (Num is any integer denoting clinet number)
2) After 1) step type as follows:
    n1 + n2  (Addition of n1 and n2)
    n1 * n2    (Subtraction of n1 and n2)
    e^n2    (e to the power n2) 
    ni^n2   (n1 to the power n2)

    n1,n2 is any integer/float
*****************************************/



#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include <string.h>
#include <sys/types.h>
#include <sys/ipc.h>
#include <sys/msg.h>

struct my_msgbuf {
    long mtype;
    char mtext[50];
};

int main(int argc,char *argv[])
{
    /*Mtype of each Message generated by client is assigned
     value given by argv[1](command line argumnet)*/
    struct my_msgbuf buf={.mtext="",.mtype=atoi(argv[1])};
    int msqid;
    key_t key;
    /*Creating Unique Key same for both clinet and server*/
    if ((key = ftok("server.c", 'S')) == -1) {
        perror("ftok");
        exit(1);
    }

    if ((msqid = msgget(key, 0644 | IPC_CREAT)) == -1) {
        perror("msgget");
        exit(1);
    }
    /*Connecting To the queue*/
    printf("Enter lines of text, ^D to quit:\n");
    while(1){
        /*Taking Input from user and sending ito to the queue*/
        scanf("%[^\n]s",buf.mtext);
        if (msgsnd(msqid, &buf, strlen(buf.mtext)+1, 0) == -1) /* +1 for '\0' */
            perror("msgsnd");
            getchar();
    }
    /*Removing Queue after the operation completed (Not needed)*/
    if (msgctl(msqid, IPC_RMID, NULL) == -1) 
    {
        perror("msgctl");
        exit(1);
    }

    return 0;
}
